spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.eu.mailgun.org
    username: oris@mail.kaanf.com

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

oris:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "http://localhost:8080"